apiVersion: v1
kind: ConfigMap
metadata:
  name: ycs-lms-config
  namespace: ycs-lms
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-service:3306/ycs_lms?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true"
  SPRING_REDIS_HOST: "redis-service"
  SPRING_REDIS_PORT: "6379"
  FILE_UPLOAD_PATH: "/app/uploads"
  BACKUP_DIRECTORY: "/app/backups"
  DB_HOST: "mysql-service"
  DB_PORT: "3306"
  TZ: "Asia/Seoul"
  JAVA_OPTS: "-Xms1024m -Xmx2048m -XX:+UseG1GC -XX:MaxGCPauseMillis=200"