apiVersion: v1
kind: Secret
metadata:
  name: ysc-lms-secret
  namespace: ysc-lms
type: Opaque
stringData:
  # Database credentials
  SPRING_DATASOURCE_USERNAME: "ycs_user"
  SPRING_DATASOURCE_PASSWORD: "changeme"  # Change this!
  MYSQL_ROOT_PASSWORD: "changeme"  # Change this!
  MYSQL_USER: "ycs_user"
  MYSQL_PASSWORD: "changeme"  # Change this!
  DB_USER: "ycs_user"
  DB_PASSWORD: "changeme"  # Change this!
  
  # JWT Secret
  JWT_SECRET: "your-very-long-and-secure-jwt-secret-key-change-this-in-production"
  
  # External API Keys
  EMS_API_KEY: ""
  HS_CODE_API_KEY: ""
  EXCHANGE_RATE_API_KEY: ""
  
  # Email Configuration
  MAIL_HOST: "smtp.gmail.com"
  MAIL_PORT: "587"
  MAIL_USERNAME: ""
  MAIL_PASSWORD: ""