# Production Profile Configuration
spring:
  application:
    name: ycs-lms-prod

  # Database Configuration - MySQL
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/ycs_lms?useSSL=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:ycs_user}
    password: ${DB_PASSWORD:ycs_password}
    
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      idle-timeout: 600000
      connection-timeout: 30000
      max-lifetime: 3600000
      leak-detection-threshold: 60000
      pool-name: YCS-LMS-Production-Pool
      connection-test-query: SELECT 1
      auto-commit: false

  h2:
    console:
      enabled: false  # Disabled in production

  # JPA Configuration - Production
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false

  # SQL Initialization - Disabled
  sql:
    init:
      mode: never

  # Enable Flyway for production
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

# Logging - Production
logging:
  level:
    com.ysc.lms: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
