# Development Profile Configuration
spring:
  application:
    name: ycs-lms-dev

  # Database Configuration - H2 File-based (for development)
  datasource:
    # ✅ 파일 기반 H2 (데이터 영구 저장) - 운영 준비 상태
    url: jdbc:h2:file:./data/ycs-lms-dev;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    generate-unique-name: false

    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1800000
      pool-name: YCS-LMS-Dev-Pool
      connection-test-query: SELECT 1
      auto-commit: false

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false  # 보안을 위해 로컬에서만 접근 허용

  # JPA Configuration - Development
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      # ✅ For H2 memory database, use create to ensure tables exist
      ddl-auto: create          # Create tables first
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        generate_statistics: true
    defer-datasource-initialization: true

  # SQL Initialization - Disabled (use AdminInitializationRunner instead)
  sql:
    init:
      # Disable SQL initialization, use AdminInitializationRunner for admin account
      mode: never               # Disable SQL initialization
      data-locations: classpath:data.sql

  # Disable Flyway for development (use JPA auto-creation)
  flyway:
    enabled: false
    validate-on-migrate: false
    baseline-on-migrate: true

  # Mail Configuration - Gmail SMTP (Development)
  mail:
    host: ${SMTP_HOST:smtp.gmail.com}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USERNAME:monz729@gmail.com}
    password: ${SMTP_PASSWORD:eyubylejwyuqnqvj}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000
          ssl:
            trust: ${SMTP_HOST:smtp.gmail.com}
      mail.debug: ${SMTP_DEBUG:true}  # SMTP 디버깅 (개발환경에서만)
    default-encoding: UTF-8

# Server Configuration
server:
  port: 8081

# Email Notification Settings
app:
  notification:
    email:
      enabled: true   # 개발환경에서도 이메일 전송 활성화 (테스트용)
      from: monz729@gmail.com
      from-name: "YCS 물류관리시스템"

# Logging - Development
logging:
  level:
    com.ysc.lms: DEBUG
    org.springframework.security: INFO
    org.springframework.mail: INFO
    org.springframework.web: WARN
    com.ysc.lms.service.EmailService: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    org.hibernate.engine.internal.StatisticalLoggingSessionEventListener: OFF
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"