spring:
  application:
    name: ycs-lms
  
  # Active profile (default: dev)
  profiles:
    active: dev
  
  # HTTP encoding configuration
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true
      force-response: true
  
  # 자동 설정 비활성화 (개발용)
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
      - org.springframework.boot.autoconfigure.data.elasticsearch.ElasticsearchDataAutoConfiguration
      - org.springframework.boot.autoconfigure.data.elasticsearch.ElasticsearchRepositoriesAutoConfiguration
      - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
      - org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration
      - org.springframework.boot.autoconfigure.sql.init.DataSourceInitializationAutoConfiguration
      # Mail 자동 설정을 활성화 (Gmail SMTP 사용)
  
  # Database and JPA configurations are in profile-specific files

      
  # Security
  security:
    jwt:
      secret-key: YCS-LMS-2024-SECRET-KEY-FOR-JWT-TOKEN-GENERATION-MUST-BE-LONG-ENOUGH
      expiration-time: 86400000 # 24 hours in milliseconds

# JWT Configuration (for JwtUtil)
jwt:
  secret: YCS-LMS-2024-SECRET-KEY-FOR-JWT-TOKEN-GENERATION-MUST-BE-LONG-ENOUGH
  expiration: 86400000 # 24 hours in milliseconds
  refresh-expiration: 604800000 # 7 days in milliseconds
      
  # Gmail SMTP Configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: monz729@gmail.com
    password: eyubylejwyuqnqvj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  # Cache Configuration (simple for development)
  cache:
    type: simple

  # Session Configuration (in-memory for development)
  session:
    store-type: none
    timeout: 86400s  # 24 hours

  # Spring Boot File Upload Configuration
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 100MB
      file-size-threshold: 2KB
  
  # Message encoding
  messages:
    encoding: UTF-8
    fallback-to-system-locale: false

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# Logging
logging:
  level:
    com.ycs.lms: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.stat: DEBUG
    org.hibernate.engine.internal.StatisticalLoggingSessionEventListener: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    
# CORS Configuration
cors:
  allowed-origins:
    - http://localhost:3000
    - http://localhost:3001
    - http://localhost:3002
    - http://localhost:3003
    - http://localhost:3004
    - http://localhost:3005
    - http://localhost:3006  # 현재 프론트엔드 포트
    - http://localhost:3007
    - http://localhost:3008
    - http://localhost:3009
    - http://localhost:3010
    - http://127.0.0.1:3000
    - http://127.0.0.1:3001
    - http://127.0.0.1:3002
    - http://127.0.0.1:3003
    - http://127.0.0.1:3004
    - http://127.0.0.1:3005
    - http://127.0.0.1:3006
    - http://127.0.0.1:3007
    - http://127.0.0.1:3008
    - http://127.0.0.1:3009
    - http://127.0.0.1:3010
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed-headers:
    - "*"
  allow-credentials: true
  max-age: 3600

# Business Rules
business:
  cbm:
    threshold: 29.0 # CBM 임계값 (m³)
  amount:
    thb-threshold: 1500.0 # THB 임계값
  warehouse:
    auto-assign-location: true
    default-location-prefix: "A"
    
# External APIs Configuration
external-api:
  ems:
    base-url: https://mock-ems-api.com
    api-key: ${EMS_API_KEY:mock-key}
    enabled: false
  hs-code:
    base-url: https://mock-hscode-api.com
    api-key: ${HS_API_KEY:mock-key}
    enabled: false
  exchange-rate:
    base-url: https://mock-exchange-api.com
    api-key: ${EXCHANGE_API_KEY:mock-key}
    enabled: false

# HS Code API Configuration and App Settings
app:
  api:
    hscode:
      search:
        key: ${HSCODE_SEARCH_API_KEY:test-key-default}
        url: https://apis.data.go.kr/1360000/000000/getVilageFcstInfoService
        enabled: true
      tariff:
        key: ${HSCODE_TARIFF_API_KEY:test-key-default}  
        url: https://apis.data.go.kr/1360000/000000/getTariffRateService
        enabled: true
      exchange:
        key: ${HSCODE_EXCHANGE_API_KEY:test-key-default}
        url: https://apis.data.go.kr/1360000/000000/getExchangeRateService
        enabled: true
  notification:
    email:
      enabled: true
      from: monz729@gmail.com
      from-name: "YCS 물류관리시스템"
  frontend:
    base-url: http://localhost:3007
    
# File Upload Configuration

file:
  upload:
    base-path: ${FILE_UPLOAD_PATH:./uploads}
    max-size: 50MB # 최대 파일 크기
    max-request-size: 100MB # 최대 요청 크기
    temp-cleanup-hours: 24 # 임시 파일 정리 주기(시간)
    allowed-types:
      image: ["jpg", "jpeg", "png", "gif", "webp", "bmp"]
      document: ["pdf", "doc", "docx", "xls", "xlsx", "txt", "hwp"]
      archive: ["zip", "rar", "7z", "tar", "gz"]
      video: ["mp4", "avi", "mov", "wmv", "flv"]
      audio: ["mp3", "wav", "flac", "aac"]
    image:
      thumbnail:
        enabled: true
        width: 200
        height: 200
        quality: 0.8
      optimize:
        enabled: true
        max-width: 1920
        max-height: 1080
        quality: 0.85

