# Development Profile Configuration
spring:
  application:
    name: ycs-lms-dev

  # Database Configuration - H2 File-based
  datasource:
    # ✅ 파일 기반 H2 (프로젝트 폴더 아래 .h2/ycs-lms-dev.mv.db 로 저장)
    url: jdbc:h2:file:./.h2/ycs-lms-dev;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    generate-unique-name: false

    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1800000
      pool-name: YCS-LMS-Dev-Pool
      connection-test-query: SELECT 1

  h2:
    console:
      enabled: true
      path: /api/h2-console
      settings:
        web-allow-others: true

  # JPA Configuration - Development
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      # ✅ 절대 create / create-drop 쓰지 말 것 (데이터 날아감)
      ddl-auto: update          # 스키마만 변경(필요 시 컴럼 추가)
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        generate_statistics: true
    defer-datasource-initialization: true

  # SQL Initialization - Test accounts
  sql:
    init:
      # ⚠️ 파일 DB로 전환 후에는 data.sql을 매번 실행하지 않는 것이 안전
      mode: never               # seed가 필요하면 DevSeedRunner 사용
      data-locations: classpath:simple-data.sql

  # Disable Flyway for development (use JPA auto-creation)
  flyway:
    enabled: false

  # Mail Configuration - Gmail SMTP (Development)
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:monz729@gmail.com}
    password: ${MAIL_PASSWORD:eyubylejwyuqnqvj}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

# Email Notification Settings
app:
  notification:
    email:
      enabled: ${APP_NOTIFICATION_EMAIL_ENABLED:true}
      from: ${MAIL_USERNAME:monz729@gmail.com}
      from-name: "YCS 물류관리시스템"

# Logging - Development
logging:
  level:
    com.ycs.lms: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"