# Development Profile Configuration
spring:
  application:
    name: ycs-lms-dev

  # Database Configuration - H2 File-based (for testing)
  datasource:
    # ✅ 파일 기반 H2 (데이터 영구 저장)
    url: jdbc:h2:file:./.h2/ycs-lms-dev;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    generate-unique-name: false

    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1800000
      pool-name: YCS-LMS-Dev-Pool
      connection-test-query: SELECT 1

  h2:
    console:
      enabled: true
      path: /h2-console   # ← /api 붙이지 마세요
      settings:
        web-allow-others: true

  # JPA Configuration - Development
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      # ✅ For H2 memory database, use create to ensure tables exist
      ddl-auto: create          # Create tables first
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        generate_statistics: true
    defer-datasource-initialization: true

  # SQL Initialization - Disabled (using AdminInitializationRunner instead)
  sql:
    init:
      # Disable SQL initialization, use AdminInitializationRunner for admin account
      mode: never               # Disable SQL initialization
      data-locations: classpath:data.sql

  # Disable Flyway for development (use JPA auto-creation)
  flyway:
    enabled: false
    validate-on-migrate: false
    baseline-on-migrate: true

  # Mail Configuration - Gmail SMTP (Development)
  mail:
    host: smtp.gmail.com
    port: 587
    username: monz729@gmail.com
    password: eyubylejwyuqnqvj
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 5000
      mail.smtp.writetimeout: 5000
    default-encoding: UTF-8

# Server Configuration
server:
  port: 8081

# Email Notification Settings
app:
  notification:
    email:
      enabled: false  # 개발환경에서는 이메일 전송 비활성화
      from: monz729@gmail.com
      from-name: "YCS 물류관리시스템"

# Logging - Development
logging:
  level:
    com.ycs.lms: DEBUG
    org.springframework.security: INFO
    org.springframework.mail: INFO
    org.springframework.web: WARN
    com.ycs.lms.service.EmailService: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    org.hibernate.engine.internal.StatisticalLoggingSessionEventListener: OFF
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"