spring:
  application:
    name: ycs-lms-test
  
  # Database Configuration - H2 메모리 사용 (테스트용)
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 5000
      idle-timeout: 30000

  h2:
    console:
      enabled: ${H2_CONSOLE_ENABLED:true}
      path: /h2-console
      settings:
        web-allow-others: false  # 테스트 환경에서도 보안 고려

  # JPA Configuration - 테스트용 최적화
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop  # 테스트 후 정리
      show-sql: ${HIBERNATE_SHOW_SQL:false}
    show-sql: false
    defer-datasource-initialization: true
    
  # SQL 초기화
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
      
  # Mail Configuration - 테스트용 (실제 발송 안함)
  mail:
    host: ${SMTP_HOST:localhost}
    port: ${SMTP_PORT:25}
    username: ${SMTP_USERNAME:test}
    password: ${SMTP_PASSWORD:test}
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

# 서버 설정
server:
  port: 8081
  servlet:
    context-path: /api

# 로깅 - 기본만
logging:
  level:
    com.ysc.lms: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.security: DEBUG