# YCS LMS Development Configuration
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/ycs
    username: sa
    password: ycs
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true

        # JPA Configuration - DISABLED for MyBatis migration
        # jpa:
        #   hibernate:
        #     ddl-auto: create-drop
        #   show-sql: true
        #   properties:
        #     hibernate:
        #       format_sql: true
        #       dialect: org.hibernate.dialect.H2Dialect

        # Redis Configuration (disabled for dev)
        # data:
        #   redis:
        #     host: localhost
        #     port: 6379
        #     timeout: 2000ms
        #     lettuce:
        #       pool:
        #         max-active: 8
        #         max-idle: 8
        #         min-idle: 0

  # Data Initialization - 테스트 데이터 로딩 활성화
  sql:
    init:
      #      mode: always
      #      data-locations: classpath:data-dev.sql
      platform: h2

logging:
  level:
    com.ycs.lms: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: INFO
    org.mybatis: DEBUG
    org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLogger: OFF
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/ycs-lms-local.log

app:
  jwt:
    # Base64 인코딩된 64바이트(512bit) 이상 키 필요
    secret: ${JWT_SECRET:eWNzTG1zTG9jYWxTZWNyZXRLZXkyMDI0U3VwZXJTZWN1cmVUb2tlbkZvckpXVFVBVVRIZXh0cmFMb25nU2VjcmV0S2V5Rm9yNTEyQml0c0hNQUNTaGE1MTJTdXBwb3J0}
    expiration: 86400000        # 24 hours
    refresh-expiration: 604800000 # 7 days
    issuer: ${JWT_ISSUER:ycs-lms}
    clock-skew: ${JWT_CLOCK_SKEW:30} # seconds

  cors:
    allowed-origins:
      - http://localhost:3000
      - http://localhost:5173
      - http://localhost:5175
      - http://127.0.0.1:3000
      - http://127.0.0.1:5173
      - http://localhost:*
      - http://127.0.0.1:*
    allowed-methods: [GET, POST, PUT, DELETE, OPTIONS]
    allowed-headers: ["*"]
    allow-credentials: true

  security:
    bcrypt-strength: 10

  business-rules:
    cbm-threshold: 29.0
    high-value-threshold-thb: 1500.0
    member-code-grace-period-days: 30

  external-apis:
    ems:
      url: ${EMS_API_URL:https://api.test.com/ems}
      key: ${EMS_API_KEY:test-key}
      timeout: 10000
      fallback-enabled: true
    hs-code:
      url: ${HS_API_URL:https://api.test.com/hs}
      key: ${HS_API_KEY:test-key}
      timeout: 10000
      fallback-enabled: true
    exchange-rate:
      url: ${EXCHANGE_API_URL:https://api.exchangerate-api.com/v4/latest/THB}
      timeout: 5000

  file-storage:
    type: local
    base-path: ${java.io.tmpdir}/ycs-lms-uploads
    max-file-size: 10MB
    allowed-types: [image/jpeg, image/png, image/gif, application/pdf, text/plain, application/json]

  notification:
    email-enabled: false
    sms-enabled: false

mybatis:
  # 리소스 폴더 실제 경로와 일치하도록 수정 (mapper, not mappers)
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ycs.lms.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true
    use-column-label: true
    use-generated-keys: true
    default-executor-type: reuse
    default-statement-timeout: 60000
  config-location: classpath:mybatis-config.xml

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

debug: true
