# YCS LMS Local Development Configuration
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
      
  # Data Initialization - 로컬 테스트 데이터 로딩
  sql:
    init:
      mode: always
      data-locations: classpath:data-local.sql
      platform: h2
          
  # Mail Configuration (mock for local)
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USER:local@gmail.com}
    password: ${SMTP_PASS:localpassword}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /api
    
# Logging Configuration
logging:
  level:
    com.ycs.lms: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.mybatis: DEBUG
    org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLogger: OFF
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/ycs-lms-local.log

# Application Configuration
app:
  jwt:
    secret: ${JWT_SECRET:eWNzTG1zTG9jYWxTZWNyZXRLZXkyMDI0U3VwZXJTZWN1cmVUb2tlbkZvckpXVEFVVEhleHRyYUxvbmdTZWNyZXRLZXlGb3I1MTJCaXRzSE1BQ1NoYTUxMlN1cHBvcnQ=}
    expiration: 86400000 # 24 hours
    refresh-expiration: 604800000 # 7 days
    
  cors:
    allowed-origins:
      - http://localhost:3000
      - http://localhost:5173
      - http://localhost:5175
      - http://127.0.0.1:3000
      - http://127.0.0.1:5173
      - http://localhost:*
      - http://127.0.0.1:*
    allowed-methods:
      - GET
      - POST  
      - PUT
      - DELETE
      - OPTIONS
    allowed-headers:
      - "*"
    allow-credentials: true
    
  security:
    bcrypt-strength: 4  # 로컬에서는 빠른 처리를 위해 낮은 강도
    password-policy:
      min-length: 4  # 로컬에서는 간단한 패스워드 허용
      require-uppercase: false
      require-lowercase: false
      require-numbers: false
      require-special-chars: false
      
  business-rules:
    cbm-threshold: 29.0
    high-value-threshold-thb: 1500.0
    member-code-grace-period-days: 30
    
  external-apis:
    ems:
      url: ${EMS_API_URL:http://localhost:9001/mock/ems}
      key: ${EMS_API_KEY:local-test-key}
      timeout: 30000  # 로컬에서는 긴 타임아웃
      fallback-enabled: true
    hs-code:
      url: ${HS_API_URL:http://localhost:9001/mock/hs}
      key: ${HS_API_KEY:local-test-key}
      timeout: 30000
      fallback-enabled: true
    exchange-rate:
      url: ${EXCHANGE_API_URL:http://localhost:9001/mock/exchange}
      timeout: 30000
      
  file-storage:
    type: local
    base-path: ${java.io.tmpdir}/ycs-lms-local-uploads
    max-file-size: 50MB  # 로컬에서는 큰 파일 허용
    allowed-types:
      - image/jpeg
      - image/png  
      - image/gif
      - application/pdf
      - text/plain
      - application/json
      
  notification:
    email-enabled: false
    sms-enabled: false
    
# MyBatis Configuration
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.ycs.lms.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false  # 로컬에서는 캐시 비활성화로 실시간 반영
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true
    use-column-label: true
    use-generated-keys: true
    default-executor-type: reuse
    default-statement-timeout: 60000  # 로컬에서는 긴 타임아웃
  config-location: classpath:mybatis-config.xml

# Management Endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"  # 로컬에서는 모든 엔드포인트 노출
  endpoint:
    health:
      show-details: always
      
# Development Features
debug: true
