# YCS LMS Production Configuration
spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/ycs_lms_prod?useSSL=true&serverTimezone=Asia/Bangkok}
    username: ${DB_USERNAME:ycs_user}
    password: ${DB_PASSWORD:ycs_secure_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1200000
      connection-timeout: 30000
      leak-detection-threshold: 60000
      
  # Redis Configuration for production caching
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 2
          max-wait: 2000ms
          
  # Mail Configuration (production SMTP)
  mail:
    host: ${SMTP_HOST:smtp.gmail.com}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USER:noreply@ycs.com}
    password: ${SMTP_PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: "*"

# Server Configuration
server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  http2:
    enabled: true
    
# Logging Configuration
logging:
  level:
    com.ycs.lms: INFO
    org.springframework.security: WARN
    org.springframework.web: WARN
    org.mybatis: WARN
    org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLogger: OFF
    root: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
  file:
    name: /var/log/ycs-lms/application.log
    max-size: 100MB
    max-history: 30
    total-size-cap: 1GB

# Application Configuration
app:
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION:3600000} # 1 hour for production
    refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000} # 7 days
    
  cors:
    allowed-origins:
      - ${FRONTEND_URL:https://ycs.com}
      - ${ADMIN_URL:https://admin.ycs.com}
    allowed-methods:
      - GET
      - POST  
      - PUT
      - DELETE
      - OPTIONS
    allowed-headers:
      - Authorization
      - Content-Type
      - X-Requested-With
    allow-credentials: true
    
  security:
    bcrypt-strength: 12  # 강력한 보안을 위해 높은 강도
    password-policy:
      min-length: 8
      require-uppercase: true
      require-lowercase: true
      require-numbers: true
      require-special-chars: true
      
  business-rules:
    cbm-threshold: ${CBM_THRESHOLD:29.0}
    high-value-threshold-thb: ${HIGH_VALUE_THRESHOLD:1500.0}
    member-code-grace-period-days: ${GRACE_PERIOD_DAYS:30}
    
  external-apis:
    ems:
      url: ${EMS_API_URL}
      key: ${EMS_API_KEY}
      timeout: 5000
      fallback-enabled: false
      retry-count: 3
    hs-code:
      url: ${HS_API_URL}
      key: ${HS_API_KEY}
      timeout: 5000
      fallback-enabled: false
      retry-count: 3
    exchange-rate:
      url: ${EXCHANGE_API_URL:https://api.exchangerate-api.com/v4/latest/THB}
      timeout: 3000
      retry-count: 2
      
  file-storage:
    type: ${STORAGE_TYPE:s3}  # S3 또는 local
    base-path: ${STORAGE_BASE_PATH:/app/uploads/prod}
    s3:
      bucket: ${S3_BUCKET:ycs-lms-files}
      region: ${S3_REGION:ap-southeast-1}
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    max-file-size: 5MB
    allowed-types:
      - image/jpeg
      - image/png  
      - application/pdf
      
  notification:
    email-enabled: true
    sms-enabled: ${SMS_ENABLED:true}
    slack:
      webhook-url: ${SLACK_WEBHOOK_URL}
      channel: ${SLACK_CHANNEL:#alerts}
    
# MyBatis Configuration
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.ycs.lms.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true
    use-column-label: true
    use-generated-keys: true
    default-executor-type: reuse
    default-statement-timeout: 15000  # 운영환경에서는 짧은 타임아웃
  config-location: classpath:mybatis-config.xml

# Management Endpoints - 보안을 위해 제한적 노출
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
      show-components: when-authorized
  metrics:
    export:
      prometheus:
        enabled: ${PROMETHEUS_ENABLED:false}
        
# Security Headers
server:
  servlet:
    session:
      timeout: 30m
      cookie:
        secure: true
        http-only: true
        same-site: strict

# Production Features
debug: false

# SSL Configuration (if using embedded server)
server:
  ssl:
    enabled: ${SSL_ENABLED:false}
    key-store: ${SSL_KEYSTORE_PATH:}
    key-store-password: ${SSL_KEYSTORE_PASSWORD:}
    key-store-type: ${SSL_KEYSTORE_TYPE:PKCS12}
