# YCS LMS Production Configuration (Patched)
spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/ycs_lms_prod?useSSL=true&serverTimezone=Asia/Bangkok}
    username: ${DB_USERNAME:ycs_user}
    password: ${DB_PASSWORD:ycs_secure_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1200000
      connection-timeout: 30000
      leak-detection-threshold: 60000
  sql:
    init:
      mode: never
  mail:
    host: ${SMTP_HOST:smtp.gmail.com}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USER:noreply@ycs.com}
    password: ${SMTP_PASS:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: "*"

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api

logging:
  level:
    com.ycs.lms: INFO
    org.springframework.security: WARN
    org.springframework.web: INFO
    org.mybatis: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

app:
  jwt:
    secret: ${JWT_SECRET:PLEASE_SET_BASE64_SECRET_64B_OR_MORE}
    expiration: 86400000
    refresh-expiration: 604800000
    issuer: ${JWT_ISSUER:ycs-lms}
    clock-skew: ${JWT_CLOCK_SKEW:30}
  cors:
    allowed-origins:
      - ${CORS_ALLOWED_ORIGIN_1:https://ycs.example.com}
      - ${CORS_ALLOWED_ORIGIN_2:https://app.ycs.example.com}
    allowed-methods: [GET, POST, PUT, DELETE, OPTIONS]
    allowed-headers: ["*"]
    allow-credentials: true
  security:
    bcrypt-strength: 12
    password-policy:
      min-length: 8
      require-uppercase: true
      require-lowercase: true
      require-numbers: true
      require-special-chars: false
  business-rules:
    cbm-threshold: 29.0
    high-value-threshold-thb: 1500.0
    member-code-grace-period-days: 30
  external-apis:
    ems:
      url: ${EMS_API_URL:https://api.test.com/ems}
      key: ${EMS_API_KEY:change-me}
      timeout: 10000
      fallback-enabled: true
    hs-code:
      url: ${HS_API_URL:https://api.test.com/hs}
      key: ${HS_API_KEY:change-me}
      timeout: 10000
      fallback-enabled: true
    exchange-rate:
      url: ${EXCHANGE_API_URL:https://api.exchangerate-api.com/v4/latest/THB}
      timeout: 5000
  file-storage:
    type: ${FILE_STORAGE_TYPE:local}
    base-path: ${FILE_BASE_PATH:/var/lib/ycs-lms/uploads}
    max-file-size: 10MB
    allowed-types: [image/jpeg, image/png, image/gif, application/pdf]
  notification:
    email-enabled: true
    sms-enabled: false

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ycs.lms.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true
    use-column-label: true
    use-generated-keys: true
    default-executor-type: reuse
    default-statement-timeout: 25000
  config-location: classpath:mybatis-config.xml

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
  endpoint:
    health:
      show-details: always

debug: false
