# YCS LMS Default Configuration
# This file contains common settings shared across all profiles

spring:
  application:
    name: ycs-lms
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
    
  # 공통 Jackson 설정
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false
    time-zone: Asia/Bangkok
    date-format: yyyy-MM-dd HH:mm:ss
    
  # 공통 Web 설정
  web:
    resources:
      add-mappings: true
      static-locations: classpath:/static/
    
  # 공통 Servlet 설정
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB
      
  # 공통 Transaction 설정
  transaction:
    default-timeout: 30
    rollback-on-commit-failure: true

# 공통 서버 설정
server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false
  tomcat:
    max-threads: 200
    min-spare-threads: 10
    
# 공통 애플리케이션 설정
app:
  version: @project.version@
  name: YCS LMS
  description: YCS Learning Management System
  
  # 공통 보안 설정
  security:
    remember-me-key: ${REMEMBER_ME_KEY:ycs-lms-remember-me-key-2024}
    session-timeout: 1800 # 30 minutes
    
  # 공통 페이징 설정
  pagination:
    default-size: 20
    max-size: 100
    
  # 공통 캐시 설정
  cache:
    default-ttl: 3600 # 1 hour
    user-cache-ttl: 1800 # 30 minutes
    
---
# Profile별 활성화 안내
spring:
  config:
    activate:
      on-profile: "!local & !dev & !production"
      
logging:
  level:
    root: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - Profile not specified. Please set SPRING_PROFILES_ACTIVE to one of: local, dev, production"
