spring:
  application:
    name: ycs-lms
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
    
  datasource:
    url: jdbc:h2:mem:ycs_lms;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
      
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: ycs-lms-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.ycs.lms.dto"
        
  mail:
    host: ${SMTP_HOST:smtp.gmail.com}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USER:}
    password: ${SMTP_PASS:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          timeout: 5000
          connectiontimeout: 5000
          
  # JPA configuration removed - using MyBatis
  sql:
    init:
      mode: always
      schema-locations: classpath:db/migration/V1__Create_base_tables.sql
      data-locations: classpath:data-h2.sql
    
# MyBatis Configuration
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.ycs.lms.entity
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    multiple-result-sets-enabled: true
    use-generated-keys: true
    auto-mapping-behavior: partial
    auto-mapping-unknown-column-behavior: warning
    cache-enabled: true
    call-setters-on-nulls: true
    return-instance-for-empty-row: false
    shrink-whitespaces-in-sql: true
    
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    
server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api
    
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      
logging:
  level:
    root: INFO
    com.ycs.lms: INFO
    org.springframework.web: WARN
    org.mybatis: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/ycs-lms.log
    
# Application specific properties
app:
  jwt:
    # 환경변수에서 강력한 Base64 인코딩된 비밀키 사용 (최소 512비트)
    secret: ${JWT_SECRET:ycs-lms-dev-secret-key-2024-super-secure-token-for-development-only}
    expiration: ${JWT_EXPIRATION:3600000} # 1 hour (기본값)
    refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000} # 7 days (기본값)
    # JWT 발급자 정보
    issuer: ${JWT_ISSUER:ycs-lms}
    # 허용되는 클럭 스큐 (초)
    clock-skew: ${JWT_CLOCK_SKEW:300}
    
  cors:
    allowed-origins: ${CORS_ORIGINS:http://localhost:3000,http://localhost:5173}
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "*"
    allow-credentials: true
    
  file:
    upload-dir: ${FILE_UPLOAD_DIR:./uploads}
    max-size: 10485760 # 10MB
    allowed-extensions: jpg,jpeg,png,pdf,doc,docx,xls,xlsx
    
  external-api:
    ems:
      url: ${EMS_API_URL:}
      key: ${EMS_API_KEY:}
      timeout: 30000
    hs-code:
      url: ${HS_API_URL:}
      key: ${HS_API_KEY:}
      timeout: 30000
    exchange-rate:
      url: ${EXCHANGE_RATE_API_URL:}
      key: ${EXCHANGE_RATE_API_KEY:}
      timeout: 10000
      
  business-rules:
    cbm-threshold: 29.0
    thb-amount-threshold: 1500.0
    auto-air-conversion: true
    require-member-code: true
    enterprise-approval-days: 2
    partner-approval-days: 2
    
  recaptcha:
    site-key: ${RECAPTCHA_SITE_KEY:}
    secret-key: ${RECAPTCHA_SECRET_KEY:}
    verify-url: https://www.google.com/recaptcha/api/siteverify