# YCS LMS Development Configuration (Patched)
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/ycs
    username: sa
    password: ycs
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: embedded
      # 기존 data-dev.sql은 존재하지 않아 실패 → 실제 존재하는 파일로 교체
      data-locations: classpath:data-h2.sql
      platform: h2

logging:
  level:
    com.ycs.lms: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: INFO
    org.mybatis: DEBUG
    org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLogger: OFF
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/ycs-lms-dev.log

app:
  jwt:
    secret: ${JWT_SECRET:PLEASE_SET_BASE64_SECRET_64B_OR_MORE}
    expiration: 86400000
    refresh-expiration: 604800000
    issuer: ${JWT_ISSUER:ycs-lms}
    clock-skew: ${JWT_CLOCK_SKEW:30}
  cors:
    allowed-origins:
      - ${DEV_FRONTEND_ORIGIN:https://dev.ycs.example.com}
      - http://localhost:5173
    allowed-methods: [GET, POST, PUT, DELETE, OPTIONS]
    allowed-headers: ["*"]
    allow-credentials: true
  security:
    bcrypt-strength: 10
  business-rules:
    cbm-threshold: 29.0
    high-value-threshold-thb: 1500.0
    member-code-grace-period-days: 30
  external-apis:
    ems:
      url: ${EMS_API_URL:https://api.test.com/ems}
      key: ${EMS_API_KEY:test-key}
      timeout: 10000
      fallback-enabled: true
    hs-code:
      url: ${HS_API_URL:https://api.test.com/hs}
      key: ${HS_API_KEY:test-key}
      timeout: 10000
      fallback-enabled: true
    exchange-rate:
      url: ${EXCHANGE_API_URL:https://api.exchangerate-api.com/v4/latest/THB}
      timeout: 5000
  file-storage:
    type: local
    base-path: ${java.io.tmpdir}/ycs-lms-uploads
    max-file-size: 10MB
    allowed-types: [image/jpeg, image/png, image/gif, application/pdf]
  notification:
    email-enabled: false
    sms-enabled: false

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ycs.lms.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true
    use-column-label: true
    use-generated-keys: true
    default-executor-type: reuse
    default-statement-timeout: 25000
  config-location: classpath:mybatis-config.xml

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
  endpoint:
    health:
      show-details: always

debug: true
